export const GET_CONTENT_START = "GET_CONTENT_START";
export const POST_CREATE = "POST_CREATE";
export const SET_LIKE_ADD = "SET_LIKE_ADD";
export const SET_DISLIKE_ADD = "SET_DISLIKE_ADD";
export const CREATE_COMMENT_TO_COMMENT = "CREATE_COMMENT_TO_COMMENT";
export const CREATE_COMMENT = "CREATE_COMMENT";
