export const SET_TOKEN = "SET_TOKEN";
export const REMOVE_TOKEN = "REMOVE_TOKEN";
export const SET_USER_INFO = "SET_USER_INFO";
export const REMOVE_USER_INFO = "REMOVE_USER_INFO";
export const CHANGE_STATUS_LIKE = "CHANGE_STATUS_LIKE";
export const CHANGE_STATUS_COMMENT = "CHANGE_STATUS_COMMENT";
export const CHANGE_STATUS_OLD = "CHANGE_STATUS_OLD";

export const PROFILE_EDIT = "PROFILE_EDIT";
